use_frameworks!

platform :ios, '8.0'

target 'PodPrivateDemo_Example' do
  pod 'PodPrivateDemo', :podspec => '../PodPrivateDemo.podspec'

  target 'PodPrivateDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
